# Generated by Django 4.2.4 on 2023-08-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_usernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='only_user',
        ),
    ]
